### PR TITLE
Alice/v2.2.8

### PR DESCRIPTION
**Pull request by mfasDa**

### CODE REVIEW

**Comment by mfasDa** [comment]
@qgp @maireiphc Could we please import version 2.2.8 of SHERPA and create a new tag for this. Update of the build recipe should come as a second step and require
- Link agains LHAPDF6
- Add dependency on openloops (needed for NLO matrix element calculation) - needs new repository and build recipe
- Add dependency on fastjet (needed for kinematic cuts when running dijet processes)
- Enable SHERPA python API

(@lcunquei added in cc)

**Comment by ktf** [comment]
I would suggest that you do not patch the manuals building here, but you do so in `alidist`, so that we can simply import upstream.

**Review by ktf — CHANGES_REQUESTED** [review]
Please, move the change to avoid building the manuals in alidist.

**Comment by mfasDa** [comment]
@ktf Indeed this would be the preferred option and would make life easier, particularly as SHERPA now also moved the repository to git (gitlab). Unfortunately there is no option in the configure file  switching off building the manual, so moving to the build recipe won't work and patching the Makefile is still needed. I assume that also for previous releases switching of building the manuals would have been moved to the build recipe if such an option existed.

**Comment by mfasDa** [comment]
Can we merge this and tag so that we can adapt the build recipe build recipe building from the alisw source?

**Comment by mfasDa** [comment]
@ktf @maireihpc Thanks a lot!

Can we please create the following now:
- branch alice/v2.2.8 from master
- tag v2.2.8-alice1 from alice/v2.2.8

Thanks in advance!

**Comment by maireiphc** [comment]
Hi Markus,

  I have created a branch v2.2.8 from master as requested (PAG-MC owns alidisit/SHERPA so that I can do it).
I was about to go on and tag as requested v2.2.8-alice1 as a new release, but then looking at https://github.com/alisw/SHERPA, I figured out that there are, on master, relics from older alisw/SHERPA, I mean files that were left untouched by your yesterday's bump to 2.2.8 (
AUTHORS, README, + all the makefile.am in any subdir + ... ?)

Just a check : is it all ok for you ? i.e. no contaminant left and the code is in fact clean as you intended to ?
(I believe that @qgp had a different habit for any update of the master when bumping to a new release version.: 
- completely clean the repository (git rm everything) 
- download the source for the official site here https://sherpa-team.gitlab.io/changelog.html meaning : https://sherpa.hepforge.org/downloads/?f=SHERPA-MC-2.2.8.tar.gz or git clone -b rel-2-2-8 https://gitlab.com/sherpa-team/sherpa.git 
- commit a fresh and genuine release )

**Comment by mfasDa** [comment]
Hi @maireiphc ,

When creating the branch for the new SHERPA version I removed all files after creating the branch, and synced the files from the new SHERPA version there. What I did not do was a git rm (but just an rm). Indeed I would have preferred cleaning this. Unfortunately I have to make pull requests in the master branch while owners can push branches there (which I think is what Jochen did). So when merging from master you might always have files which are unchanged.

In any case the branch I created is not contaminated by remnants of the old SHERPA versions. Only these couple of files seem to not have changed between the two SHERPA versions.

Cheers

Markus

**Comment by qgp** [comment]
Hi @mfasDa, @maireiphc,

Yes, I usually did `git rm -rf *` in master, unpacked the new version, `git add *`, tag master as vX.Y.Z. And (only) in case ALICE patches are needed, branch alice/vX.Y.Z from master, apply patches, tag as vX.Y.Z-aliceN. But indeed this workflow relies on having write access to the repo.

Cheers,
   Jochen

**Pull request merged**
